In [1]:
import numpy as np 

In [2]:
# np.dot
# # vectors (1-D)array it compute the dot product of the vector
# # matrices (2-D)array ,it perform matrix multiplication
## mixed dimension it treat them as 1-D vector and return the output product of them
# Dot product of two vectors
# vector1 = np.array([1, 2, 3])
# vector2 = np.array([4, 5, 6])
# dot_product_vectors = np.dot(vector1, vector2)
# # Output: 32 (1*4 + 2*5 + 3*6)
# Matrix multiplication 
# matrix1 = np.array([[1, 2], [3, 4]]) 
# matrix2 = np.array([[5, 6], [7, 8]])
# dot_product_matrices = np.dot(matrix1, matrix2) 
# # Output: [[19 22]
# import numpy as np

# # Outer product of two vectors
# vector1 = np.array([1, 2, 3])
# vector2 = np.array([4, 5, 6])
# outer_product = np.outer(vector1, vector2)
# # Output: [[ 4  5  6]
# #          [ 8 10 12]
# #          [12 15 18]]



In [10]:
class HebbianLearning:
    
    def __init__(self,input_size,output_size):
        self.weights=np.zeros((input_size,output_size))
    
    def train(self,inputs,outputs):
        for x,y in zip(inputs,outputs):
            self.weights+=np.outer(x,y)
    
    def predict(self,inputs):
        return np.dot(inputs,self.weights)
    
            

In [11]:
input_size = 3
output_size = 2
hebbian = HebbianLearning(input_size, output_size)

# Training data
inputs = np.array([[1, 0, -1], [0, 1, 1], [1, 1, 0], [1, 1, -1]])
outputs = np.array([[1, 0], [0, 1], [1, 1], [0, 0]])

# Train the model
hebbian.train(inputs, outputs)

# Predict
test_input = np.array([1, 0, 1])
prediction = hebbian.predict(test_input)

print("Weights after training:\n", hebbian.weights)
print("Prediction for test input [1, 0, 1]:", prediction)


Weights after training:
 [[ 2.  1.]
 [ 1.  2.]
 [-1.  1.]]
Prediction for test input [1, 0, 1]: [1. 2.]
